### ISSUE TITLE
False Positive EventBridge Quota alert

### ISSUE THREAD

**Issue by cpuppos** [aws-solutions/quota-monitor-for-aws#175] opened 2023-11-14 12:44 UTC
**Describe the bug**

Receiving alerts against many accounts for this same quota threshold breached

Service: EventBridge|
Region: | us-east-1 |  
Service: | EventBridge |  
Limit Name: | PutEvents throttle limit in transactions per second

example of threshold crossed

Current Usage: | 84.96000000000001 |  
Limit Amount: | 100

When we look at the current quota in service quota we see this quota applied to all of the accounts alerting.

PutEvents throttle limit in transactions per second
Request increase at account-level
Details
Description
Maximum number of requests per second for PutEvents API. Additional requests are throttled.
Quota code
L-9B653E91
Utilization
0
Applied quota value
10,000
AWS default quota value
10,000
Adjustability
Account-level

**To Reproduce**

N/A

**Expected behavior**

N/A

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.0.0]

6.2.4

- [ ] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository? - No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? - N/A
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? - Yes
- [ ] Were there any errors in the CloudWatch Logs? [How to enable debug mode?] - N/A (https://docs.aws.amazon.com/solutions/latest/quota-monitor-for-aws/troubleshooting.html)

**Screenshots**

**Additional context**

**Comment by abe-aws** [comment] 2023-11-14 14:01
Thanks for the report.

The Quota Monitor solution refreshes the list of [supported services and quotas](https://docs.aws.amazon.com/general/latest/gr/aws-service-information.html) that can be monitored every month. This is caused by the increased number of quotas supported as of a few weeks ago. The [documentation](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-quota.html) lists the limit to the number of invocations for different regions. It also states that, you won't lose any events.
```
An invocation is an event matching a rule and being sent on to the rules targets. After the limit is reached, the invocations are throttled; that is, they still happen but they are delayed.
```
Quotas are checked every 6 or 12 hours per configuration. That means notification delays caused by throttling from EventBridge don't have a meaningful impact how the solution works. So we won't be issuing an immediate patch fix for this.

But there will be two features in an upcoming release that would resolve this issue:
1 - Option to turn off 'OK' events.
2 - Option to select the period of quota checks. Currently, it's hard coded to 1 hour. Selecting a longer period will result in less event bridge rule invocations.

**Comment by lwalter** [comment] 2023-11-14 17:32
Hi @abe-aws thanks for your response. Coincidentally we are also receiving errors upon every quota check, currently 12 hours in our configuration. Additionally we are monitoring > 12 AWS accounts, and 3 regions each account with this solution. So we are receiving a LOT of emails for L-5540C5E3 and L-9B653E91.

As it stands receiving such a high volume of emails while waiting for another release is not desirable. To that end we have attempted to ignore these two quota codes following https://docs.aws.amazon.com/solutions/latest/quota-monitor-for-aws/step-6.-configure-notifications-optional.html which has had no impact on the quotas being checked and we are still receiving emails.

Could you confirm that this is the desirable to path to take while waiting for a release to remedy this issue? If so could you confirm the following configuration should indeed ignore those quotas from being checked?

![Screenshot 2023-11-14 at 9 30 42 AM](https://github.com/aws-solutions/quota-monitor-for-aws/assets/4431554/81d363a7-34a1-4069-adcc-a8a0002f1cb4)

Thank you.

**Comment by abe-aws** [comment] 2023-11-14 17:59
Yes, the approach is correct. But the values should be of the form `ServiceCode[:QuotaCode|QuotaName|Resource]` - in this case `EventBridge:L-9B653E91,EventBridge:L-5540C5E3` or simply `EventBridge:*` (which mutes all notifications from EventBridge).

**Comment by stepkirk** [comment] 2023-11-14 19:00
FWIW, we also started receiving a LOT of alerts for these two EventBridge limits every 12 hours. This started on November 10th for us. Nice to know we are not the only ones. :-)

I have put in the two suggested mutes to keep the alerts down in the future.

Curious why this started when it did and then continues like clockwork. Was wondering if it was something we changed or something AWS did.

**Comment by tivanov-qb** [comment] 2023-11-15 06:18
+1 on this issue

**Comment by abe-aws** [comment] 2023-11-15 14:25
It happens like clockwork because the lambda function responsible from monitoring quotas (QMCWPoller) is invoked every every 12 or 6 hours per configuration. That results in 12 or 6 events (with a period of an hour) for every quota monitored. It's not something you changed, the [Service Quotas service](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) is continuously adding support for more services and quotas.

Changing the monitoring frequency to 6 hours should help. That is a parameter in the template SQ Template. If your deployment is on an organization or organizational unit, you will have to [update](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-update.html) the stackset - QM-SQ-Spoke-StackSet - to update the parameter.

**Comment by stepkirk** [comment] 2023-11-15 18:10
Thanks for the detailed explanation @abe-aws. Makes sense. I kinda like the twice-a-day cadence for quota alerts for us. Knowing I can mute the new/noisy ones that pop up is good for now. 

Alerts will make more sense to the unknowing when you add the % sign in a future release.

Appreciate the your team and the time you put into the tool. It is helpful to us. 😄

**Comment by nickste** [comment] 2023-11-28 00:32
Hi folks - I'm a Product Manager on Amazon EventBridge. Thanks for raising the issue here and my apologies that it's taken us this long to catch it. We can confirm an issue with Event Bus metrics for utilization calculations for service quotas related to invocations and PutEvents. Currently the quota utilization metrics for invocations and PutEvents are calculated using a per minute period of time, while the quota itself is enforced on a per second period of time. This results in the percentage utilization metrics for invocations and PutEvents appearing higher than expected, which could in turn trigger any CloudWatch Alarms configured for these quotas. The issue was introduced on 11/9/2023 17:00 PST. A fix is currently being deployed and is expected to be in place in all Regions by the end of day 11/27 (Pacific time). Apologies for any inconveniences this caused.

**Closed** 2023-12-05 16:45 UTC
Labels: bug, triaged
