### ISSUE TITLE
ValidationError: MetricDataQueries.member.X.Id Not Matching Expected Pattern

### ISSUE THREAD

**Issue by gulnurkaztai** [aws-solutions/quota-monitor-for-aws#200] opened 2024-09-22 18:51 UTC
**Describe the bug**

When deploying the AWS Quota Monitor solution using the third deployment scenario (single account within an OU), multiple ValidationErrors are occurring in the Lambda function `SO0005 quota-monitor-for-aws - QM-ListManager-Function`. The errors persist regardless of the account type used for deployment:
An account within an Organizational Unit (OU)
A standalone AWS account created outside of the organization

**To Reproduce**

1. Deploy the AWS Quota Monitor solution using the third deployment scenario (single account within an OU).
2. Manually deploy the hub (no OU) stack and SQ spoke stack in the AWS console.
3. Check the logs for the Lambda function SO0005 quota-monitor-for-aws - QM-ListManager-Function.

**Expected behavior**

The solution should deploy and function without ValidationErrors related to MetricDataQueries formatting.

**Please complete the following information about the solution:**

- Version v6.2.9
- Region: us-east-1, us-east-2
- Was the solution modified from the version published on this repository? No
- Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- Were there any errors in the CloudWatch Logs? Yes, ValidationErrors as described

<img width="1554" alt="Screenshot 2024-09-22 at 2 45 42 PM copy" src="https://github.com/user-attachments/assets/db55c1bf-3299-4d02-9812-3a7f8c359edd">

**Comment by sanjay-reddy-kandi** [comment] 2024-09-23 14:12
Thank you for reporting this issue. We will investigate the root cause, which may be due to some changes by the Service Quotas team. We'll provide updates and a resolution as soon as possible.

**Comment by sanjay-reddy-kandi** [comment] 2024-09-23 20:40
We have found out the root case and will release a patch this week

**Comment by gulnurkaztai** [comment] 2024-09-24 17:11
Sounds good. Thank you!

**Comment by sanjay-reddy-kandi** [comment] 2024-10-14 15:09
This is issue is fixed in the latest version `v6.2.11`

**Closed by sanjay-reddy-kandi** 2024-10-14 15:09 UTC
Labels: bug
